/*
  output.tf
*/

/*
  Outputs the values of the provided arguments
  below.
*/

output "user_name" {
  value       = aws_iam_user.user
  description = "Outputs Usernames from the users list in users.tfvars.json as well as the ARN generated from creating the new user account."
}

output "fingerprint" {
  value       = aws_iam_user_login_profile.user_profile[*]
  description = "Outputs the key generated by PGP fingerpring for encryption on the new user creation"
}

output "credentials" {
  value = {
    "key"      = aws_iam_access_key.user_key[*]
    "password" = data.pgp_decrypt.user_password_decrypt[*]
  }
  description = "Outputs the Access Key and Password for the user accounts with the sensitive tag to prevent revealing the details in the tfstate file"
  sensitive   = true
}